sudo: required
services:
  - docker

before_install:
  - docker build -t sabyagupta/docker-test -f Dockerfile.dev .

script:
  - docker run sabyagupta/docker-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-459725583713"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secret: "$AWS_SECRET_KEY"
